### ISSUE TITLE
adding permissions to user

### ISSUE THREAD

**Issue by dieg0nob** [UpperM/guacamole-powershell#1]
It's posible to add the permission to a guacauser, "chance own password" ?
i can't find what's the name of this permission.
![IMG_8003](https://user-images.githubusercontent.com/29979144/78714250-f02aa700-78f1-11ea-96ad-f788248c9212.jpg)

**Comment by UpperM** [comment]
I didn't have implemented users permissions.

It's in progress

**Comment by UpperM** [comment]
Added in commit https://github.com/UpperM/guacamole-powershell/commit/ec6fbc94ebab3b52a27d4f7b399e624ac48a910b

Download the latest release to use the new functions https://github.com/UpperM/guacamole-powershell/releases/tag/v1.0.2

**Comment by dieg0nob** [comment]
work like a charm!
Thanks !
great proyect
