### ISSUE TITLE
Cannot create new connections

### ISSUE THREAD

**Issue by djdeant** [UpperM/guacamole-powershell#14]
With Guacamole 1.3.0 I cannot create new connections.  I get error message:

VERBOSE: POST with -1-byte payload
WARNING: The remote server returned an error: (500) Internal Server Error.

Tried new tokens, but nothing seems to work.

**Comment by UpperM** [comment]
Hi,

Can you add your script ?

Do you use HTTP or HTTPS connection ?

Thank
