### ISSUE TITLE
Enable checkbox at Usergroup for ConnectionGroup below Root

### ISSUE THREAD

**Issue by L3B1gM4c** [UpperM/guacamole-powershell#15]
[Add-GuacUserGroupConnectionGroup.txt](https://github.com/UpperM/guacamole-powershell/files/7987138/Add-GuacUserGroupConnectionGroup.txt)

**Comment by UpperM** [comment]
Hello,

Please can you describe this function ? Or add screenshot of what is doing.

Thanks

**Comment by L3B1gM4c** [comment]
Bonjour Matthieu,

I setup a ps script for creating users, groups, connections and connections groups on Guacamole. (saml+adfs, mysql)
Your ps commands are working fine for me but some commands are missing :-)

- User creation is working
- UserGroup creation is working
- Connection creation is working
- ConnectionGroup creation is working

To get all together you need to add
- Add all ConnectionGroups above (like a tree) to the UserGroup (read permissions, on webpage the checkbox)
- Add the Users to the UserGroup
- Add the Connections to the UserGroup (read permissions, on webpage the checkbox)

If the ConnectionGroups are not set to read at the Usergroup the Connections on the Guacamole start page are not visible

![guac user interface](https://user-images.githubusercontent.com/98893356/152311731-6da7cc0b-075a-464f-a271-ed97288db7e0.png)

In the backend the Usergroup with the checkbox enabled for the ConnectionGroup it looks like this:

![guac usergroup interface (admin)](https://user-images.githubusercontent.com/98893356/152312508-3479ca04-4660-4338-b42f-ca99c7e977cf.png)

BR Martin

**Comment by UpperM** [comment]
Hello,

Thank for the explanations.

I've modified ``Add-GuacUserGroupConnection()`` in commit 52865e7. Now the function check if the connection has parents and set correct permissions. 

I'm working on the function for adding a connection group permission (with child) to a user group.

**Comment by UpperM** [comment]
I've added ``Add-GuacUserGroupConnectionGroup``
https://github.com/UpperM/guacamole-powershell/blob/master/PSGuacamole/Public/UserGroups/Add-GuacUserGroupConnectionGroup.ps1
Example :
```Powershell
Add-GuacUserGroupConnectionGroup -DataSource $DataSource -Group "Test-Group" -ConnectionGroupName "IPMI"
```

Result : 
![2022-02-03_21-31-01](https://user-images.githubusercontent.com/13823969/152423928-7e1bbe4c-a3cd-4bca-857f-5fb75c1d20fb.png)

For now it's doesn't work if I set ``-ConnectionGroupName "IPMI-SUB"`` because it's a sub group. I need to do more tests.
