### ISSUE TITLE
Possible Error in Add-GuacConnectionGroupMember

### ISSUE THREAD

**Issue by yokhoe** [UpperM/guacamole-powershell#19]
I don't believe this URI for this API call is written correctly... Or maybe I'm not looking at the right one for Assigning Connection Group to User Group.  It shouldn't require a username as an argument.
![image](https://user-images.githubusercontent.com/22972701/178075993-97821450-4b2c-4657-b844-74997a4f769d.png)

**Comment by UpperM** [comment]
Hello @yokhoe,

Hum Add-GuacConnectionGroupMember is for add a user to a connection group. 

You want to add a user group to a connection group ?
