### ISSUE TITLE
reset user totp 

### ISSUE THREAD

**Issue by dieg0nob** [UpperM/guacamole-powershell#2]
plans to implement reset totp's users ?

**Comment by jamlazevedo** [comment]
can you use when the totp's extension is enable? who set authentication code for connection?

**Comment by UpperM** [comment]
I'm not sure, I need to check but I didn't find any mentions of TOTP in API documentation.

**Comment by jamlazevedo** [comment]
@UpperM Thkxs for your great work. Workaround to use TOPT is new function new-GuacToken to use   authentication code or use token retrieve from browser after authentication TOTP.

**Comment by UpperM** [comment]
@jamlazevedo Oh ok it's not related to this issues.

Yes you can get the token when you are connected on Guacamole with TOTP and then in your script set theses variables 

```Powershell
$Token = "YOURTOKEN"
$Server = "http://yourserver/"
```
https://puu.sh/Fny63/d38889a859.png

**Comment by jamlazevedo** [comment]
@UpperM thkxs
