### ISSUE TITLE
Get-connection not showing all information from GUI profile

### ISSUE THREAD

**Issue by pdtit** [UpperM/guacamole-powershell#4]
Hi, I'm fairly new to Guacamole, but got everything up-and-running and created 2 users and 2 connections, 1 for each user. From the Guac admin console, I can see the connection linked to a user, but not when I'm running get-user or get-connection from PShell. 

Also, when running get-connection, it is not showing all settings I defined from the GUI (ignore cert, security,...); any idea how to get that information?

**Comment by UpperM** [comment]
> 
> 
> Hi, I'm fairly new to Guacamole, but got everything up-and-running and created 2 users and 2 connections, 1 for each user. From the Guac admin console, I can see the connection linked to a user, but not when I'm running get-user or get-connection from PShell.

You can retrive the linked connections of the user with the parameter ``-Details permissions`` of ``Get-GuacUser``

Example : 
````PowerShell
Get-GuacUser -DataSource mysql -Username "john.doe@fontenay-aux-roses.fr" -Details permissions
````
Return 
````PowerShell
connectionPermissions       : @{55=System.Object[]} // This is the linked connection
connectionGroupPermissions  :
sharingProfilePermissions   :
activeConnectionPermissions : @{}
userGroupPermissions        :
systemPermissions           : {}
````


> Also, when running get-connection, it is not showing all settings I defined from the GUI (ignore cert, security,...); any idea how to get that information?

Yup I need to add a new function ``Get-GuacConnectionParameters``

**Comment by pdtit** [comment]
Hi Matthieu, thanks for the fast and working reply, very much appreciated! I got most of it working now, so trying to integrate this in a broader setup provisioning automation flow. Also trying to do the same from REST API directly - testing with Postman for now, but it should all become part of a custom process. Thanks for your help!!

**Comment by UpperM** [comment]
> Also, when running get-connection, it is not showing all settings I defined from the GUI (ignore cert, security,...); any idea how to get that information?

I recheck the code and you can get these informations with the ``-Details $True`` parameters

Example : 
```PowerShell
Get-GuacConnection -DataSource mysql -ConnectionId 52 -Details $True
```
Return

```
hostname      : PC-001
password      : ${GUAC_PASSWORD}
security      : nla
ignore-cert   : true
port          : 3389
width         : 1920
server-layout : fr-fr-azerty
height        : 1080
username      : ${GUAC_USERNAME}
```

> That said, I sometimes face some weird issues, for example running get-guacuserS provides the list of all users; but when running get-guacuser, it gives an error 500

Did you specifiy the ``-Username`` parameter ?
