### ISSUE TITLE
Get-GuacUser doesn't work because of an extra slash.

### ISSUE THREAD

**Issue by jasampson** [UpperM/guacamole-powershell#5]
It looks like you've got an extra slash in line 34 of `Get-GuacUser.ps1`, which is causing malformed URLs to be used when calling the API resulting in HTTP 500 errors.  

You should change this:
```
    begin
    {
        $Uri = "$Server/api/session/data/$($DataSource)/users/$($Username)/"

        if ($Details)
        {
            $Uri = "$Uri/$Details"
        }

```
to this (notice the first `$Uri = ` line and the removal of the last slash on the right):
```
    begin
    {
        $Uri = "$Server/api/session/data/$($DataSource)/users/$($Username)"

        if ($Details)
        {
            $Uri = "$Uri/$Details"
        }
```
Also, huge thank you for sharing your awesome powershell module with the world.

**Comment by UpperM** [comment]
Thank it's fix.
